### ISSUE TITLE
Add New Spot FAB

### ISSUE THREAD

**Issue by dhochman** [dhochman/Skatespot-Organizer#10]
This issue is to consider removing the add/plus new spot FAB. It might simplify things to only allow the user to create a new spot by putting a marker on the map and then clicking the marker to launch the SpotDetailActivity with the marker's coordinates. Thinking ahead about data-related issues, we may want to have the longitude-latitude coordinates of a Spot act as a primary key that must be unique (so that the user can't create multiples spots with the same coordinates). We could even enforce that the coordinates are not within a certain radius of one another (we treat coordinates within 1 kilometer of each other as really the same spot).

In line with this thinking, we may want enforce that every spot must have coordinates, and one good way to do that would be to remove the add New Spot FAB.

**Comment by tryn2hard** [comment]
As much as I hate having to scrap the work I've put towards the Fab, I think it's the right call to get rid of it. The logistics to get the Fab fully operational is too much of a headache

**Comment by tryn2hard** [comment]
Since we're agreed about taking out the FAB, I'm going to close this issue.
