### ISSUE TITLE
Image Sizes

### ISSUE THREAD

**Issue by tryn2hard** [dhochman/Skatespot-Organizer#12]
### Description

Currently, there are images being displayed in the following places: custom info window, Master list (listView, GridView), and Spot Detail. What kind of dimensions should we standardized for each of the activities that are displaying spot images?

**Comment by dhochman** [comment]
Not sure I understand. Are you talking about having fixed dimensions for the images? Shouldn't we scale the images appropriately to fill their space in the view?

**Comment by tryn2hard** [comment]
I just reread what I had written, and it doesn't make sense to me either. I guess I'm asking to found out what resolution we save the pics as?

**Comment by dhochman** [comment]
I think the pics should be stored in full resolution in the file system (that will be the master copy). Then, when we load the pics into their different views (in the info window, list, grid, and spot detail) we should scale them appropriately. I've heard that this is where Glide excels; it does a lot of the performance scaling for us. I haven't used Glide so I don't know the details, but I imagine you may be able to tell Glide which View to fill with which photo and it will scale the photo suitably.
