### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by tryn2hard** [dhochman/Skatespot-Organizer#5]
@dhochman 

Yo dude thanks for coming out to the house warming. Minji and I were happy to see you and Areum.  If you haven't figured it out by now, I've been making good use of that birthday gift haha 

![Image of Rick Burning the House Down](https://i.imgur.com/d4DvSek.gif)

**Comment by dhochman** [comment]
Haha, yeah man, we had fun; thanks for hosting!

**Comment by tryn2hard** [comment]
First practical use of GitHub Essentials
